# Generated by Django 4.1 on 2022-08-22 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list_category_comment_bids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='category_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
