# Generated by Django 4.1 on 2022-08-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_list_category_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
