# Generated by Django 4.1 on 2022-08-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='user_time_bid',
            field=models.DateTimeField(),
        ),
    ]
