# Generated by Django 4.1 on 2022-08-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='auctio_status',
            field=models.BooleanField(default=True),
        ),
    ]
