# Generated by Django 4.1 on 2022-08-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_list_auctio_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='auctio_status',
            new_name='auction_status',
        ),
    ]
