# Generated by Django 4.1 on 2022-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_auctio_status_auction_list_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='auction_status',
            field=models.BooleanField(),
        ),
    ]
